<?php

/**
 * Implements hook_preprocess_page()
 */
function manuscrito_preprocess_page(&$vars) {
    $vars['get']['name'] = $_GET['name'];
}

function manuscrito_theme($existing, $type, $theme, $path) {
    return array(
        'listing_display' => array( // list node saved
            'variables' => array('id_node' => NULL),
            'template' => 'listing-list',
        ),
        'type_display' => array( // list type node
            'template' => 'type-list',
        ),
        'form_list' => array( // create node
            'variables' => array('markup' => NULL,'type' => NULL),
            'template' => 'form-list',
        ),
        'form_comments' => array( // create comments
            'variables' => array(
                'markup' => NULL,
                'type' => NULL,
                'revision' => NULL
            ),
            'template' => 'form-comments',
        ),
        'thanks_list' => array( // article saved message
            'variables' => array('type' => NULL,'id' => NULL),
            'template' => 'thank-list',
        ),
        'error_list' => array( // error message
            'variables' => array(
                'title' => NULL,
                'body' => NULL
            ),
            'template' => 'error-list',
        ),
        'update_locked' => array( // error message
            'variables' => array('id' => NULL),
            'template' => 'update-locked',
        ),
        'search' => array( // buscador
            'variables' => array(
                'users' => NULL,
                'name' => NULL,
                'tipo' => NULL,
                'autor' => NULL,
                'data' => NULL,
            ),
            'template' => 'search',
        ),
        'access' => array( // mis accesos
            'variables' => array(
                'users' => NULL,
            ),
            'template' => 'access-list',
        ),
        // proceso editorial
        'article_qualify' => array( 
            'variables' => array(
                'markup' => NULL,
                'type' => NULL
            ),
            'template' => 'article-qualify',
        ),
        'history_autor' => array( 
            'variables' => array(
                'data' => NULL,
                'type' => NULL,
            ),
            'template' => 'history-autor',
        ),
        'history_revisor' => array(
            'variables' => array(
                'type' => NULL,
                'data' => NULL,
            ),
            'template' => 'history-revisor',
        ),
        'history_editor' => array( 
            'variables' => array(
                'type' => NULL,
                'data' => NULL,
            ),
            'template' => 'history-editor',
        ),
        'assign_revisor' => array(
            'variables' => array(
                'markup' => NULL,
                'type' => NULL,
                'revision' => NULL
            ),
            'template' => 'assign-revisor',
        ),
    );
}